# Compiling with ghc 8.6.4
resolver: lts-13.17

# To use ghc 4.4 try:
# resolver: lts-12.24

packages:
 - .

flags:
 xmobar:
   all_extensions: true

extra-deps:
 - iwlib-0.1.0
 - libmpd-0.9.0.9

# Add to extra-deps for lts-12.24:
# - parsec-numbers-0.1.0
# - libmpd-0.9.0.9
# - alsa-mixer-0.3.0

nix:
    packages:
      - alsaLib
      - pkgconfig
      - wirelesstools
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXScrnSaver
      - zlib
